import keycode from "keycode";

export const Keys: Map<string, number> = {
  A: 65,
  ALT: 18,
  BACKSPACE: 8,
  COMMA: 188,
  DELETE: 46,
  DOWN: keycode("down"),
  END: 35,
  ENTER: keycode("enter"),
  ESC: 27,
  HOME: 36,
  LEFT: 37,
  NUMPAD_0: 96,
  NUMPAD_9: 105,
  PAGE_DOWN: 34,
  PAGE_UP: 33,
  PERIOD: 190,
  RETURN: 13,
  RIGHT: 39,
  SPACE: 32,
  TAB: keycode("tab"),
  UP: keycode("up"),
  Z: 90,
  ZERO: 48,
};
