# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Yarn lint, build, test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run linters
        run: yarn lint

      - name: Build smuggler-api
        run: yarn smuggler-api build

      - name: Build elementary
        run: yarn elementary build

      - name: Build archaeologist
        run: yarn archaeologist build:chrome:public

      - name: Build truthsayer
        # This is a little absurd, but CI=ture force react build script treat
        # all warning as errors. Let's turn it off to unblock the change. Once
        # we get rid of all the warning we cad enable CI back.
        # https://github.com/facebook/create-react-app/issues/3657
        env:
          CI: false
        run: yarn truthsayer build

      - run: yarn test --all --watchAll=false --no-watchman
